DROP TABLE IF EXISTS transaktion CASCADE;
DROP TABLE IF EXISTS kunde CASCADE;
DROP TABLE IF EXISTS bankkonto CASCADE;
DROP TABLE IF EXISTS bankkonto_dokument CASCADE;

DROP TYPE IF EXISTS transaktion_typ;
DROP TYPE IF EXISTS dokument_typ;
