# ==============================================================================
# N o d e
# ==============================================================================
node:
  port: 3000

# ==============================================================================
# D a t e n b a n k
# ==============================================================================

# "pg-native" erfordert zusaetzlich die lokale Installation von PostgreSQL
# "better-sqlite3" erfordert Python zum Uebersetzen, wenn das Docker-Image gebaut wird

db:
  type: postgres
  #type: mysql
  #type: oracle
  #type: sqlite

  #host: localhost

  username: bankkonto
  password: p
  passwordAdmin: p
  name: bankkonto
  populate: true

# ==============================================================================
# K e y c l o a k
# ==============================================================================
# "Client Secret" muss durch die Umgebungsvariable CLIENT_SECRET gesetzt werden
keycloak:
  authServerUrl: http://localhost:8880
  realm: nest
  # siehe Keycloak Menuepunkt "Clients" > Tab "Clients list" > Spalte "Client ID"
  clientId: nest-client
  #tokenValidation: online

# ==============================================================================
# L o g g i n g
# ==============================================================================
log:
  level: debug
  #dir: ./log
  pretty: true

# ==============================================================================
# H e a l t h
# ==============================================================================
health:
  prettyPrint: true

# ==============================================================================
# M a i l s e r v e r
# ==============================================================================
mail:
  #activated: false
  host: localhost
  port: 8025
  log: false

# ==============================================================================
# T e s t s
# ==============================================================================
#test:
#  startDbServer: false
