
# ==============================================================================
# N o d e
# ==============================================================================
#node:
#  port: 3000

# ==============================================================================
# D a t e n b a n k
# ==============================================================================

# "pg-native" erfordert die Installation von PostgreSQL: Docker-Image genügt nicht
# "better-sqlite3" erfordert Python zum Uebersetzen, wenn das Docker-Image gebaut wird

db:
  type: postgres
  #type: mysql
  #type: oracle
  #type: sqlite

  host: postgres

  username: bankkonto
  password: p
  passwordAdmin: p
  name: bankkonto
  populate: true

# ==============================================================================
# K e y c l o a k
# ==============================================================================
# Client-ID muss durch die Umgebungsvariable CLIENT_ID gesetzt werden
keycloak:
  authServerUrl: http://keycloak:8080
  #authServerUrl: http://localhost:8880
  realm: nest
  # siehe Keycloak Menuepunkt "Clients" > Tab "Clients list" > Spalte "Client ID"
  clientId: nest-client
  #tokenValidation: online

# ==============================================================================
# L o g g i n g
# ==============================================================================
log:
  level: debug
  dir: /tmp
  pretty: true
  #default: true

# ==============================================================================
# H e a l t h
# ==============================================================================
health:
  prettyPrint: true

# ==============================================================================
# M a i l s e r v e r
# ==============================================================================
mail:
  #activated: false
  host: fakesmtp
  port: 8025
  log: false

# ==============================================================================
# Authentifizierung
# ==============================================================================
auth:
  # https://github.com/docker/compose/issues/6741: '' wegen $
  passwordEncoded: '$argon2i$v=19$m=4096,t=3,p=1$aaxA2v/9rRSPGkwYN+NQog$27Huii1XtD3iEd62fog+04G26LRPZMHoYCI6AGKTL8M'
