apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data-pv-claim
  namespace: bankkonto-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: kc-data-pv
  storageClassName: ""

