apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankkonto-app
  namespace: bankkonto-namespace
spec:
  replicas: 1 # Anzahl der Pods, die du haben möchtest
  selector:
    matchLabels:
      app: bankkonto-app # Label zur Auswahl der Pods
  template:
    metadata:
      labels:
        app: bankkonto-app
    spec:
      containers:
        - name: bankkonto-app
          image: calebscript/bankkonto-verwalter:2024.10.1
          volumeMounts:
          - name: bankkonto-secrets
            mountPath: /opt/app/dist/config/resources/tls  # Pfad im Container
            readOnly: true
          - name: app-config
            mountPath: /opt/app/dist/config/resources/app.yml
            readOnly: true
          # Bind Mount für das Log-Verzeichnis
          - name: log-volume
            mountPath: /opt/app/log
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: bankkonto-secrets
      volumes:
      - name: bankkonto-secrets
        secret:
          secretName: bankkonto-secrets
      # Volume für das Log-Verzeichnis
      - name: log-volume
        hostPath:
          path: /Users/gentlebookpro/Projekte/UNI/SWE/bankkonto-verwalter-nestjs/log
          type: Directory
      # Volume für die Konfiguration
      - name: app-config
        hostPath:
          path: /Users/gentlebookpro/Projekte/UNI/SWE/bankkonto-verwalter-nestjs/.extras/compose/bankkonto/app.yml
          type: File

# kubectl config view --raw > kubeconfig_ORIGINAL

#---------------------------------------------------------------------------------------------------------------------------------------------------------------------
# kubectl get pods -n bankkonto-namespace
# helm list -n bankkonto-namespace

# Überprüfe den Status des Deployments:
# kubectl describe deployment bankkonto-app -n bankkonto-namespace

# Überprüfe die Logs der Pods:
# kubectl logs bankkonto-app-59bb5ddbff-cvvmn -n bankkonto-namespace

# Prüfe die Verfügbarkeit der Anwendung:
# kubectl get svc -n bankkonto-namespace

#---------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Deinstalliere die Helm-Release
# helm uninstall bankkonto -n bankkonto-namespace


# kubectl delete deployment bankkonto-app -n bankkonto-namespace
# kubectl delete service bankkonto-service -n bankkonto-namespace
# kubectl delete configmap bankkonto-config -n bankkonto-namespace
# kubectl delete secret bankkonto-secrets -n bankkonto-namespace

# kubectl delete pvc postgres-tablespace-pv-claim -n bankkonto-namespace



# Überprüfe den Status der Ressourcen:
# kubectl get pods -n bankkonto-namespace
# kubectl get deployments -n bankkonto-namespace
# kubectl get services -n bankkonto-namespace
# kubectl get configmaps -n bankkonto-namespace
# kubectl get secrets -n bankkonto-namespace
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------


#------------------------------------------------------------------------------------------------------------------------------------------------------

# kubectl delete deployment bankkonto-app -n default
# kubectl delete service bankkonto-service -n default
# kubectl delete configmap bankkonto-config -n default
# kubectl delete secret bankkonto-secrets -n default

# helm list -n default
# kubectl get all -n default | grep bankkonto
