apiVersion: v1
kind: PersistentVolume
metadata:
  name: kc-data-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/gentlebookpro/Projekte/UNI/SWE/zimmermann/volumes/keycloak

