apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-data
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/gentlebookpro/Projekte/UNI/SWE/zimmermann/volumes/postgres/data

  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-tablespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/gentlebookpro/Projekte/UNI/SWE/zimmermann/volumes/postgres/tablespace

  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-csv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/gentlebookpro/Projekte/UNI/SWE/zimmermann/volumes/postgres/csv

  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-sql
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/gentlebookpro/Projekte/UNI/SWE/zimmermann/volumes/postgres/sql

  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-config
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/gentlebookpro/Projekte/UNI/SWE/zimmermann/volumes/postgres/postgresql.conf

  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-certs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/gentlebookpro/Projekte/UNI/SWE/bankkonto-verwalter-nestjs/src/config/resources/tls
---
