apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: bankkonto-namespace
data:
  POSTGRES_HOST_AUTH_METHOD: trust
  postgresql.conf: |
    ssl = on
    ssl_cert_file = '/var/lib/postgresql/certificate.crt'
    ssl_key_file = '/var/lib/postgresql/key.pem'
