apiVersion: v1
kind: Service
metadata:
  name: bankkonto-service
  namespace: bankkonto-namespace
spec:
  selector:
    app: bankkonto-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
