name: Continuous Deployment to Local Kubernetes Cluster

on:
  workflow_dispatch:  # Manuelles Auslösen des Workflows

jobs:
  deploy:
    runs-on: self-hosted  # Oder 'ubuntu-latest', falls du auf Linux arbeitest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Kubernetes context
      run: |
        # Setze den kubectl Kontext auf deinen lokalen Docker Desktop Cluster
        kubectl config use-context docker-desktop

    - name: Apply Postgres PersistentVolume
      run: |
        kubectl apply -f ./persistent-volumes/ --namespace=bankkonto-namespace
        kubectl apply -f ./namespace.yml --namespace=bankkonto-namespace
        kubectl apply -f ./postgres --namespace=bankkonto-namespace
        kubectl apply -f ./keycloak --namespace=bankkonto-namespace
        kubectl apply -f ./pgadmin --namespace=bankkonto-namespace
        kubectl apply -f ./bankkonto --namespace=bankkonto-namespace

    - name: Wait for Deployment Rollout
      run: |
        # Warte, bis das Deployment erfolgreich ausgerollt ist
        kubectl rollout status deployment/bankkonto-app -n bankkonto-namespace
