name: CI/CD Pipeline Docker + Kubernetes

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Nur Versionstags (z.B. v1.0.0)
  pull_request:
    branches:
      - main

env:
  node-versions: [20.x, 22.x, 23.x]  # Node.js-Versionen f端r alle relevanten Jobs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(env.node-versions) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Cache f端r schnelleres Build

      - name: Verify dist directory
        run: ls -la

      # - name: Cleanup previous builds
      #   run: |
      #     rm -rf node_modules dist .extras/doc/api .extras/doc/folien/folien.html .extras/doc/projekthandbuch/html

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Compile TypeScript
        run: npx tsc

      - name: Verify dist directory
        run: ls -l

      - name: Upload dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - name: Upload node_modules
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules

  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(env.node-versions) }} # Wiederverwendung der Node.js-Version vom build-Job
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Download node_modules
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: node_modules

      # - name: Install dependencies
      #   run: npm ci

      - name: Lint code
        run: npm run eslint

      - name: Security audit
        run: npm audit --omit=dev

      - name: Generate documentation (TypeDoc)
        run: npm run typedoc

      # - name: Generate slides (reveal.js)
      #   run: npm run revealjs

      # - name: Compile AsciiDoc
      #   run: npm run asciidoctor

  package:
    runs-on: ubuntu-latest
    needs: [build, analyze]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Dist2
        run: mkdir dist

      - name: Download dist folder
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Verify dist directory
        run: ls -l

      - name: Package distribution
        run: zip -r dist.zip dist

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: dist-package
          path: dist.zip

  docker:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Build Docker image
        run: "echo 'TODO: Docker-Image bauen und veroeffentlichen'"

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy to Kubernetes
        run: "echo 'TODO: Deployment f端r Kubernetes durchf端hren'"
