name: Test Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  kubernetes_cleanup:
    name: Cleanup Kubernetes Resources
    runs-on: [self-hosted]
    if: github.actor == 'Caleb-Script'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubernetes context
        run: |
          # Setze den kubectl Kontext auf deinen lokalen Docker Desktop Cluster
          kubectl config use-context docker-desktop

      - name: Delete Kubernetes Resources
        run: |
          cd .extras/kubernetes
          kubectl delete namespace bankkonto-namespace || true
          kubectl delete persistentvolume postgres-pv-data || true
          kubectl delete persistentvolume postgres-pv-tablespace || true
          kubectl delete persistentvolume postgres-pv-csv || true
          kubectl delete persistentvolume postgres-pv-sql || true
          kubectl delete persistentvolume postgres-pv-config || true
          kubectl delete persistentvolume postgres-certs-pv || true
          kubectl delete persistentvolume pgadmin-pv || true
          kubectl delete persistentvolume pgadmin4-pv || true
          kubectl delete persistentvolume kc-data-pv || true

  test:
    name: Test (lokal)
    runs-on: [self-hosted]
    needs: kubernetes_cleanup
    if: github.actor == 'Caleb-Script'

    steps:
      # - name: Install Docker Compose
      #   run: |
      #     curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
      #     chmod +x /usr/local/bin/docker-compose

      - name: path
        run: ls -al
        
      - name: Print ref name
        run: echo "This workflow was triggered by ${{ github.ref_name }}"

      - name: Print actor (Collaborator)
        run: echo "The actor is ${{ github.actor }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Create log file
        run: |
          mkdir -p log
          touch log/server.log

      - name: Set up TLS files from secrets
        env:
          TLS_KEY: ${{ secrets.TLS_KEY }}
          TLS_CERT: ${{ secrets.TLS_CERT }}
        run: |
          echo "$TLS_KEY" > src/config/resources/tls/key.pem
          # echo "$TLS_CERT" > src/config/resources/tls/certificate.crt

      - name: Set up ENV files from secrets
        env:
          KEYCLOAK_ENV: ${{ secrets.KEYCLOAK_ENV }}
          POSTGRES_ENV: ${{ secrets.POSTGRES_ENV }}
        run: |
          cd .extras/compose/backend
          echo "$KEYCLOAK_ENV" > keycloak/.env
          echo "$POSTGRES_ENV" > postgres/.env

      - name: Start Keycloak container
        run: |
          cd .extras/compose/backend
          docker-compose up -d

      - name: Jest Config aus Secret setzen
        run: echo "${{ secrets.JEST_CONFIG }}" > .jest.config.js


      - name: Run Integration Tests with Jest
        run: npm t || true

      - name: Run Coverage Tests with Istanbul
        run: npm run test:istanbul || true

      - name: Upload Jest Test Coverage
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage
          path: ./coverage

      - name: fahre keycloak und postgres runter
        run: |
          cd .extras/compose/backend/keycloak
          docker-compose down


  security:
    name: Security Scans (OWASP Dependency Check, SonarQube, Snyk)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Caching)
        run: npm ci

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
           path: node_modules
           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-node-

      - name: Install OWASP Dependency-Check
        run: |
          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v11.1.0/dependency-check-11.1.0-release.zip -o dependency-check-11.1.0-release.zip
          unzip dependency-check-11.1.0-release.zip -d dependency-check
          chmod +x dependency-check/dependency-check

      - name: Run OWASP Dependency Check
        run: |
          dependency-check/dependency-check/bin/dependency-check.sh --project "Bankkonto" --scan . --nvdApiKey ${{ secrets.NVD_API_KEY }} --format "HTML" --out dependency-check-report

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: ./dependency-check-report/*.html

      # - name: Set up Java 17
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'

      # - name: SonarQube Scan
      #   uses: sonarsource/sonarcloud-github-action@v1
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: "-Dsonar.projectKey=bankkonto -Dsonar.organization=acme.org"

      # - name: Authenticate with Snyk
      #   run: |
      #     snyk auth ${{ secrets.SNYK_TOKEN }}

      # - name: Run Snyk Test
      #   run: |
      #     snyk test --all-projects

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USER }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Run Docker Scout CVE Scan
      #   run: docker scout cves --format json calebscript/bankkonto-verwalter:2024.10.1

      # - name: Run Docker Scout Quickview
      #   run: docker scout quickview --format json calebscript/bankkonto-verwalter:2024.10.1

      # - name: Run Trivy Scan
      #   uses: aquasecurity/trivy-action@0.28.0
      #   with:
      #     image-ref: calebscript/bankkonto-verwalter:2024.10.1
      #     format: table
      #     severity: HIGH,CRITICAL



  lint:
    name: Linting and Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run eslint  # Linting-Befehl, um Code-Qualität zu prüfen
